const nodemailer = require("nodemailer");

const sendMail = async (req, res) => {
  let testAccount = await nodemailer.createTestAccount();

 const transporter = nodemailer.createTransport({
    host: 'smtp.ethereal.email',
    port: 587,
    auth: {
        user: 'generated by ethereal',
        pass: 'generated by ethereal'
    }
});
  async function main() {
      // send mail with defined transport object
      const info = await transporter.sendMail({
          from: '"Ishit Sethi👻" <karlee36@ethereal.email>', // sender address
          to: "ishitsethi678@gmail.com", // list of receivers
          subject: "Hello ✔", // Subject line
          text: "Hello world?", // plain text body
          html: "<b>Hebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbllo world?</b>", // html body
        });
        
        console.log("Message sent: %s", info.messageId);
        res.send(info);

}

main();
}

module.exports = sendMail;
